version: '3'
services:
  supply-chain-app:
    build: .
    ports:
      - '5000:5000'
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=benjamin
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
